### ISSUE TITLE
# add select/deselect all function 

### ISSUE THREAD

**Issue by edwardlennonjr** [codingbanana/DamElevCDF#1]
This runs;

observeEvent(input$selectall,{
    #if(input$selectall == 0) return(NULL) 
    #else if (input$selectall %% 2 != 0) {
    if (input$selectall %% 2 != 0) {
      updateCheckboxGroupInput(session,
                   inputId = "interceptor", 
                   label = "Choose one or more interceptor systems",
                   choices = levels(d$Interceptor),
                   selected = levels(d$Interceptor),
                   inline = T)
    } else {
      updateCheckboxGroupInput(session,
                   inputId = "interceptor", 
                   label = "Choose one or more interceptor systems",
                   choices = levels(d$Interceptor),
                   inline = T)
    }
})

**Comment by codingbanana** [comment]
The function has been added.
